// Order flow
export const CAR_INITIAL_LIST_ACTION = "CAR_INITIAL_LIST_ACTION";
export const CAR_FILTRED_LIST_ACTION = "CAR_FILTRED_LIST_ACTION";

export const ORDER_TYPE_MUTATION = "ORDER_TYPE_MUTATION";
export const CAR_INITIAL_LIST_MUTATION = "CAR_INITIAL_LIST_MUTATION";
export const CAR_FILTRED_LIST_MUTATION = "CAR_FILTRED_LIST_MUTATION";
export const CAR_RESET_FILTRED_LIST_MUTATION =
  "CAR_RESET_FILTRED_LIST_MUTATION";
export const SET_RENTED_CAR_MUTATION = "SET_RENTED_CAR_MUTATION";

// User Position and Markers
export const INIT_USER_GEO_ACTION = "INIT_USER_GEO_ACTION";

export const INIT_USER_GEO_MUTATION = "INIT_USER_GEO_MUTATION";
export const MAP_MUTATION = "MAP_MUTATION";
export const MARKERS_BY_CAR_LIST_MUTATION = "MARKERS_BY_CAR_LIST_MUTATION";

// default values
export const ORDER_TYPE_DEFAULT = "map";
